### ISSUE TITLE
why 'ef' 'watch' 'user-secrets' not added to the list? 

### ISSUE THREAD

**Issue by DaneSpiritGOD** [natemcmaster/dotnet-tools#103]
though these global tools are bundled, they should be in the list.
you can mark them as official.
many dotnetcore novices don't known them.

**Comment by natemcmaster** [comment]
Same reason `dotnet build` and `dotnet restore` aren't listed. These are considered built-in subcommands of `dotnet` and the majority of users should not need to install these as a package. The only reason these tools were shipped to nuget.org was because a very small number of customers using the ["source built" SDK](https://github.com/dotnet/source-build/) also wanted access to these tools. Unless you're one of these users, I would recommend using the built-in versions of these commands.
