### ISSUE TITLE
Consider suggesting nuget.org's advanced search

### ISSUE THREAD

**Issue by loic-sharma** [natemcmaster/dotnet-tools#210]
Hello,

I am from the team that runs nuget.org. We recently added a feature that lets you search for .NET tools. Do you think it would make sense to mention the advanced search experience on the dotnet-tools repo? If so, I'd be happy to send a pull request! 😊

Blog: https://devblogs.microsoft.com/nuget/advanced-search-on-nuget-org/
Documentation: https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages

Example gif:

![image](https://user-images.githubusercontent.com/15097183/89361433-21d53400-d680-11ea-82c9-a6d65bd2fdc7.gif)

**Comment by natemcmaster** [comment]
Thanks for letting me know about this feature. I started this repo a few years ago because NuGet.org lacked the ability to search by package type. Now that is available, I think I will just update this to point to a link like https://www.nuget.org/packages?packagetype=dotnettool&sortby=totalDownloads-desc&prerel=True.

Given that, is there any benefit to keeping this repo list? I can't think of one

**Comment by loic-sharma** [comment]
> Given that, is there any benefit to keeping this repo list?

People that watch this repo get notifications whenever someone adds a new .NET tool. That's still very useful in my opinion 😊

**Comment by natemcmaster** [comment]
Done. Added a link to the top of the page. I'll keep the list in case users want to edit.
